#!/bin/bash

# Check if wget, nano, and unrar are installed
if ! command -v wget > /dev/null; then
  echo "wget is not installed. Exiting."
  exit 1
fi

if ! command -v nano > /dev/null; then
  echo "nano is not installed. Exiting."
  exit 1
fi

if ! command -v unrar > /dev/null; then
  echo "unrar is not installed. Exiting."
  exit 1
fi

# Define the target directory
target_dir="/scripts"

# Check if the target directory exists, and create it if it doesn't
if [ ! -d "$target_dir" ]; then
  mkdir -p "$target_dir"
fi

# Change directory to the target directory
cd "$target_dir"

# Check if the script directory is already in the PATH
if echo "$PATH" | grep -q "$target_dir"; then
    echo "Script directory is already in PATH"
else
    # Add the script directory to the PATH
    echo "Adding script directory to PATH"
    echo "export PATH=$PATH:$target_dir" >> /etc/profile
    source /etc/profile
fi

# Check if the scripts have already been downloaded before attempting to download them again
if [ ! -f "$target_dir/unrarall" ]; then
    curl -O https://raw.githubusercontent.com/arfoll/unrarall/master/unrarall && chmod u+x "$target_dir/unrarall"
fi

if [ ! -f "$target_dir/postProcess.sh" ]; then
    curl -O https://raw.githubusercontent.com/justinglock40/unrarall-mod/main/postProcess.sh && chmod u+x "$target_dir/postProcess.sh"
fi

